# FILE: .github/workflow-templates/ci-cd-starter.yml
# LOCATION: DCCA-ISCO/.github/.github/workflow-templates/

name: DCCA Python CI/CD (Starter Template)

on:
  push:
    # Triggers on push to development and production branches
    branches: [dev, master]
  workflow_dispatch:  # Allows manual trigger

env:
  PYTHON_VERSION: '3.14'

jobs:
  # ============================================
  # JOB 1: Run Tests and Quality Checks
  # This section remains in the Starter file to ensure tests always run first
  # ============================================
  test-and-quality:
    name: Tests & Code Quality
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v6
      
    - name: Set up Python and Install dependencies
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        cache: 'pip'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt

    # ============================================
    # 2. UNIT TESTS (ADD AS NEEDED)
    # ============================================
    - name: Run Unit Tests (Example Only)
      run: echo "Running pytest tests defined in Starter Workflow..."
      

    # ============================================
    # 2. DEPENDENCY VULNERABILITY SCANNING
    # ============================================
    - name: Security - Dependency Vulnerability Scan (pip-audit)
      run: |
        echo "========================================="
        echo "Scanning for vulnerable dependencies"
        echo "========================================="
        pip-audit --desc --requirement requirements.txt
      continue-on-error: false

    - name: Security - Check with Safety
      run: |
        echo "========================================="
        echo "Running Safety security check"
        echo "========================================="
        safety check --json || true
      continue-on-error: true

    - name: Security - Bandit Security Linter
      run: |
        echo "========================================="
        echo "Running Bandit security analysis"
        echo "========================================="
        bandit -r app.py -f json -o bandit-report.json || true
        bandit -r app.py -f screen
      continue-on-error: true
    - name: Test Summary
      if: always()
      run: echo "Code Quality Checks Passed. Ready for deployment."

    # ============================================
    # 3. LINTING
    # ============================================
    - name: Lint with flake8
      run: |
        echo "========================================="
        echo "Running flake8 linting"
        echo "========================================="
        # Stop the build if there are Python syntax errors or undefined names
        flake8 app.py --count --select=E9,F63,F7,F82 --show-source --statistics
        # Exit-zero treats all errors as warnings
        flake8 app.py --count --max-complexity=10 --max-line-length=127 --statistics --exit-zero
      continue-on-error: false

    - name: Lint with pylint
      run: |
        echo "========================================="
        echo "Running pylint analysis"
        echo "========================================="
        pylint app.py --exit-zero --max-line-length=127 || true
      continue-on-error: true

    # ============================================
    # 5. ENVIRONMENT VARIABLE VALIDATION (UNCOMMENT IF USING SECRETS)
    # ============================================
    # - name: Validate Environment Configuration
    #   run: |
    #     echo "========================================="
    #     echo "Validating Environment Configuration"
    #     echo "========================================="
    #     python -c "
    #     import os

    #     required_vars = [
    #         'EXAMPLE SECRETS HERE',

    #     ]

    #     print('Required environment variables for production:')
    #     for var in required_vars:
    #         print(f'  - {var}')

    #     print('\n✓ Environment validation check passed')
    #     print('Note: Actual values will be loaded from secrets in deployment')

    # ============================================
    # TEST SUMMARY (REMOVE / ADD COMPLETED TESTS AS NEEDED)
    # ============================================
    # - name: Test Summary
    #   if: always()
    #   run: |
    #     echo "========================================="
    #     echo "TEST PIPELINE SUMMARY"
    #     echo "========================================="
    #     echo "✓ Unit Tests: Completed"
    #     echo "✓ Security Scan: Completed"
    #     echo "✓ Linting: Completed"
    #     echo "✓ Smoke Test: Completed"
    #     echo "✓ Environment Validation: Completed"
    #     echo "========================================="


  # ============================================
  # JOB 2: Deploy to Dev Environment
  # This job CALLS the reusable SSM logic.
  # ============================================
  deploy-dev:
    name: Deploy to Dev Server
    needs: test-and-quality  # Only deploy if tests pass
    if: github.ref == 'refs/heads/dev'
    
    # CRITICAL: Calls the reusable workflow in the central repository
    # Path: Owner/Repo/.github/workflows/Filename@Ref
    uses: DCCA-ISCO/.github/.github/workflows/ssm-deploy-reusable.yml@main
    
    with:
      branch-name: dev
      server-env: development
    
    # Inherits all secrets defined at the repository and environment level
    secrets: inherit

  # ============================================
  # JOB 3: Deploy to Production Environment
  # ============================================
  deploy-prod:
    name: Deploy to Production Server
    needs: test-and-quality
    if: github.ref == 'refs/heads/master'
    
    # CRITICAL: Calls the reusable workflow in the central repository
    uses: DCCA-ISCO/.github/.github/workflows/ssm-deploy-reusable.yml@main
    
    with:
      branch-name: master
      server-env: production
    
    secrets: inherit
